version: '3.9'

services:
    nginx:
        image: nginx:alpine
        container_name: example-nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - './app:/var/www/html'
            - './docker/nginx:/etc/nginx/conf.d'
        depends_on:
            - php
        networks:
            - example-network

    php:
        image: php:8.1-fpm-alpine
        container_name: example-php
        working_dir: '/var/www/html'
        volumes:
            - './app:/var/www/html'
        networks:
            - example-network

    database:
        image: mariadb:latest
        container_name: example-database
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?err}
        networks:
            - example-network

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: example-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: database
        ports:
            - 8080:80
        depends_on:
            - database
        networks:
            - example-network

networks:
    example-network:
